function Criterios = CriteriosDeMarcha(Sim, Parametros)
%CRITERIOSDEMARCHA El carro completa el elemento y no se despega.
%   Dependen de la dinamica: con varios carros se evaluan para cada uno
%   (CriteriosDelCarro).
    Criterios = CriteriosVacios();
    Valido = ~isnan(Sim.Velocidad);

    Criterios = AgregarCriterio(Criterios, 'El carro completa el elemento', 'MayorOIgual', ...
        double(isempty(Sim.PuntoDeParada)), 1, '-', ...
        'Si falla, el carro se queda sin energia antes del final.');

    Criterios = AgregarCriterio(Criterios, 'G minima sobre el eje vertical del carro', 'MayorOIgual', ...
        min(Sim.Gz(Valido)), Parametros.GMinimaCuspide, 'G', ...
        sprintf(['Margen en la cuspide, en el punto de verificacion (%s, brazo %.3f m). ' ...
                 'N = 0 no sirve como criterio: no tolera variacion de friccion.'], ...
                Parametros.PuntoDeVerificacionNormativa, Sim.BrazoDeVerificacion));
end
