function Criterios = CriteriosDeOnset(Normativo, Escala, Parametros)
%CRITERIOSDEONSET Presupuesto de onset por eje y onset de carga (7.1.7.2).
    Criterios = CriteriosVacios();
    Ejes = {'Gx', 'Gy', 'Gz'};
    for i = 1:3
        Criterios = AgregarCriterio(Criterios, sprintf('Onset maximo de %s', Ejes{i}), 'MenorOIgual', ...
            Normativo.OnsetMaximoPorEje(i), Escala.OnsetMaximo(i), 'G/s', ...
            sprintf('Presupuesto del modelo = sqrt(lambda_loop) x %.1f G/s de la norma.', ...
                    Parametros.OnsetNormativoPorEje(i)));
    end

    Criterios = AgregarCriterio(Criterios, 'Onset de 0 G a 2 G (7.1.7.2)', 'MenorOIgual', ...
        Normativo.OnsetDeCarga, Escala.OnsetMaximo(3), 'G/s', ...
        'Alcance literal de la clausula: solo transiciones desde 0 G o menos hacia 2 G o mas.');
end
