function Lista = ParametrosDeAceptacion()
%PARAMETROSDEACEPTACION Parametros que son criterios de aceptacion.
%   Son los que fijan contra que se compara el elemento generado, en
%   cualquier modo de curvatura y para cualquier elemento. Fuente unica de
%   verdad para DescribirParametros; tiene que coincidir con lo que leen
%   ChequeosPrevios, ChequeosPosteriores, VerificarLimitesNormativos,
%   VelocidadInicialMinima y BrazoDeVerificacion.
%
%   GMinimaCuspide esta aca y NO entre los parametros del modo de curvatura:
%   es la holgura de G en la cuspide que exige la biseccion de velocidad
%   minima y la estimacion a priori de ChequeosPrevios, y vale en todos los
%   modos.

    Lista = DeclaracionDeParametros( ...
        'GMinimaCuspide',              'G',   'holgura minima de Gz en la cuspide; N = 0 no sirve como criterio', ...
        'PuntoDeVerificacionNormativa','-',   'donde se aplica la norma: ''Heartline'' (brazo d) o ''Cabeza'' (brazo d + e)', ...
        'OnsetNormativoPorEje',        'G/s', 'presupuesto de onset [Gx Gy Gz] en el prototipo; el del modelo es sqrt(lambda) veces mayor', ...
        'OnsetMaximoModelo',           'G/s', 'override directo del presupuesto del modelo; vacio = derivar de Froude', ...
        'TolObjetivoDeG',              'G',   'desvio admitido entre la G del pasajero y la que pidio el modo', ...
        'TolCierrePitch',              'rad', 'residual de cierre admitido en el giro objetivo', ...
        'AlturaMaximaDelElemento',     'm',   'altura maxima de la heartline sobre su entrada', ...
        'RadioMinimoFabricable',       'm',   'radio minimo del riel que admite la impresora', ...
        'AlturaMinimaSuelo',           'm',   'z minimo admisible del riel', ...
        'BoundingBoxDisponible',       'm',   'huella disponible, filas x, y, z', ...
        'DistanciaMinimaEntreVias',    'm',   'separacion libre exigida entre rieles', ...
        'ArcoMinimoAutointerferencia', 'm',   'vecinos por arco que la autointerferencia ignora');
end
