function Lista = ParametrosGenerales()
%PARAMETROSGENERALES Parametros del bloque 4 de ParametrosPorDefecto.
%   Fisica, resistencia al avance, tren y carro, resolucion, escalado,
%   discretizacion y tolerancias numericas: los que valen en todos los modos
%   y para todos los elementos y no son criterios de aceptacion. Misma forma
%   que ParametrosDelModo, ElementoXxx() y ParametrosDeAceptacion (ternas
%   Nombre, Unidad, Descripcion), para que DescribirParametros los imprima
%   con unidades y LayoutAJson los exporte como esquema autodescriptivo.
%
%   Entre los cuatro (modo, elemento, aceptacion, generales) tiene que quedar
%   declarado todo campo de ParametrosPorDefecto salvo ModoCurvatura, que es
%   el selector del modo y no un parametro; LayoutAJson lo verifica. Si se
%   agrega un parametro global, se declara aca.
%
%   InclinacionHelicoidalImpuesta esta en el bloque 2 del archivo de
%   parametros pero lo lee GenerarGeometria para cualquier elemento, asi que
%   se declara aca y no en un elemento.

    Lista = DeclaracionDeParametros( ...
        ... % --- Constantes fisicas ---
        'Gravedad',                    'm/s^2',  'aceleracion de la gravedad', ...
        'RhoAire',                     'kg/m^3', 'densidad del aire', ...
        ... % --- Resistencia al avance ---
        'CrrPortantes',                '-',      'coeficiente de rodadura de las ruedas portantes (de carga)', ...
        'CrrGuia',                     '-',      'coeficiente de rodadura de las ruedas guia (laterales)', ...
        'CrrRetencion',                '-',      'coeficiente de rodadura de las ruedas de retencion (up-stop)', ...
        'ModelarArrastre',             '-',      'logico: si se computa el arrastre aerodinamico', ...
        'CoefArrastre',                '-',      'coeficiente de arrastre aerodinamico del carro', ...
        'FactorTren',                  '-',      'fraccion del arrastre de flujo libre que aporta cada carro detras del primero', ...
        ... % --- Tren y carro ---
        'NumeroDeCarros',              '-',      'carros del tren', ...
        'Masa',                        'kg',     'masa del carro con el pasajero', ...
        'LargoCarro',                  'm',      'largo del carro del modelo', ...
        'AltoCarro',                   'm',      'alto del carro del modelo', ...
        'AnchoVia',                    'm',      'trocha (ancho de via) del modelo', ...
        'Holgura',                     'm',      'margen sobre la envolvente del carro para el chequeo de interferencia', ...
        'DiametroRueda',               'm',      'diametro de rueda; piso impuesto por el rodamiento minimo', ...
        'AreaFrontal',                 'm^2',    'area frontal proyectada de un carro', ...
        'DistanciaHeartline',          'm',      'del riel al centro de masa del pasajero (heartline), medida sobre U; define la via', ...
        'DistanciaHeartlineACabeza',   'm',      'de la heartline a la cabeza del pasajero, medida sobre U; solo informativa salvo verificacion en Cabeza', ...
        ... % --- Resolucion ---
        'MetodoDeAcoplamiento',        '-',      'acoplamiento geometria-dinamica: ''A'' marcha acoplada, ''B'' punto fijo, ''Ambos'' compara', ...
        'CalcularVelocidadMinima',     '-',      'logico: si se corre la biseccion de la velocidad inicial minima (cuesta decenas de generaciones)', ...
        'InclinacionHelicoidalImpuesta', '-',    'override de tan(alfa), la inclinacion de la tangente respecto del plano del giro; vacio = se resuelve por Newton', ...
        ... % --- Escalado (Froude) ---
        'RadioDeReferenciaReal',       'm',      'radio de la atraccion real que ancla lambda del loop', ...
        'LargoCarroReal',              'm',      'largo del carro real que ancla lambda del carro', ...
        ... % --- Discretizacion ---
        'PasoGeneracion',              'm',      'paso de arco de la marcha RK4 que genera la geometria', ...
        'PasoSimulacion',              'm',      'paso de arco de SimularSobreTrack', ...
        'PasosEntreOrtonormalizaciones', '-',    'cada cuantos pasos se reortonormaliza el marco (Gram-Schmidt)', ...
        'VersoresEnGrafico3D',         '-',      'flechas del marco del carro que se dibujan en la vista 3D', ...
        'PasoBusquedaVelocidad',       'm',      'paso de generacion grueso dentro de la biseccion de la velocidad minima', ...
        ... % --- Tolerancias numericas ---
        'TolNorma',                    'm',      'norma por debajo de la cual un vector se considera nulo', ...
        'TolPuntoFijo',                'm/s',    'cambio maximo de velocidad entre iteraciones del punto fijo del metodo B', ...
        'MaxIteracionesPuntoFijo',     '-',      'tope de iteraciones del punto fijo del metodo B', ...
        'MaxIteracionesCierre',        '-',      'tope de iteraciones de la correccion de cierre del giro', ...
        'MaxIteracionesAjuste',        '-',      'tope de iteraciones del ajuste de longitud de las transiciones', ...
        'MargenDeOnset',               '-',      'margen relativo que se agrega sobre la longitud justa de las transiciones en cada iteracion', ...
        'ToleranciaVelocidadDeDiseno', 'm/s',    'diferencia de velocidad de entrada que dispara aviso al re-simular un track');
end
